In [142]:
import getml
from challenge.utils.data import load_ctu_dataset

# Enable textual output to avoid rendering issues in certain JupyterLab environments
getml.utilities.progress.FORCE_TEXTUAL_OUTPUT = True

getml.set_project("db_transformer_musk_small")

Output()

Connected to project 'db_transformer_musk_small'.

# Task: MuskSmall
### Dataset Description
> <span style="font-weight: 500; color: #3b3b3b;">ⓘ️&nbsp; Generated by `gpt-4o`</span>
>
> It seems that the *MuskSmall* dataset is not available in the repository. However, I can provide a description based on the data model you provided.
> 
> *Data Model:*
> 
> The *MuskSmall* dataset consists of two tables: `conformation` and `molecule`. These tables provide information about molecular conformations and their classifications.
> 
> - **conformation**: Contains `conformation_name` (varchar), `molecule_name` (varchar), and features `f1` to `f166` (int). This table details the features of different molecular conformations.
> 
> - **molecule**: Includes `molecule_name` (varchar) and `class` (int). This table classifies molecules as either musk or non-musk.
> 
> *Task and Target Column:*
> 
> The primary task is *classification*, with the target column being `class` in the `molecule` table. The goal is to classify molecules based on their conformations.
> 
> *Column Types:*
> 
> - Varchar: `conformation_name`, `molecule_name`
> - Integer: `f1` to `f166`, `class`
> 
> *Metadata:*
> 
> - **Number of Tables**: 2
> - **Target Table**: `molecule`
> - **Target Column**: `class`
> 
> This dataset is typically used in cheminformatics to analyze and classify molecular structures based on their conformational features.

### Tables
Population table: molecule

<h4>
  <details open>
     <summary>ER Diagram</summary>
       <img src="https://relational.fel.cvut.cz/assets/img/datasets-generated/MuskSmall.svg" alt="MuskSmall ER Diagram">
   </details>
</h4>

To load the dataset, we use the `load_ctu_dataset` function from the `utils`
module. This function returns a tuple with the population table as the first
element and the a dictionary of peripheral tables as the second element.

In [143]:
molecule_raw, peripheral = load_ctu_dataset("MuskSmall")

(
    conformation,
) = peripheral.values()

In [144]:
# molecule_raw.save()
# conformation.save()

In [145]:
# molecule_raw.load()
# conformation.load()

name   conformation_name   molecule_name   f1              f2              ...   f162            f163            f164
role   unused_string       unused_string   unused_string   unused_string   ...   unused_string   unused_string   unused_string
   0   188_1+1             MUSK-188        42              -198            ...   30              48              -37
   1   188_1+2             MUSK-188        42              -191            ...   31              48              -37
   2   188_1+3             MUSK-188        42              -191            ...   30              48              -37
   3   188_1+4             MUSK-188        42              -198            ...   30              48              -37
   4   190_1+1             MUSK-190        42              -198            ...   144             43              -30
       ...                 ...             ...             ...                   ...             ...             ...
 471   jp13_1+4            NON-MUSK-jp13   49              -199            ...   134             47              -43
 472   jp13_2+1            NON-MUSK-jp13   38              -123            ...   119             79              -28
 473   jp13_2+2            NON-MUSK-jp13   43              -102            ...   121             55              -37
 474   jp13_2+3            NON-MUSK-jp13   39              -58             ...   116             79              -28
 475   jp13_2+4            NON-MUSK-jp13   52              -121            ...   95              98              -14

name   f165            f166
role   unused_string   unused_string
   0   6               30
   1   5               30
   2   5               31
   3   6               30
   4   14              26
       ...             ...
 471   -15             -10
 472   4               74
 473   -19             -36
 474   3               74
 475   12              96


476 rows x 168 columns
memory usage: 0.97 MB
type: getml.DataFrame

Now, we can inspect all tables and annotate the columns with [roles](https://getml.com/latest/user_guide/concepts/annotating_data/).

The population table (`molecule`). We already set the `target` role for the target (`class`). If the task is a multiclass classification,
we split the target column into multiple columns in an one-vs-all fashion. In this case, the original target is still avaiable as `class`.

In [146]:
molecule_pdf = molecule_raw.to_pandas()
molecule_pdf["split"] = molecule_pdf["split"].replace("val", "test")
molecule_pdf["molecule_name_2"] = molecule_pdf["molecule_name"].copy()
molecule = getml.data.DataFrame.from_pandas(molecule_pdf, name="molecule")
molecule

name          class   molecule_name   split           molecule_name_2
role   unused_float   unused_string   unused_string   unused_string
   0              0   MUSK-188        train           MUSK-188
   1              0   MUSK-190        test            MUSK-190
   2              0   MUSK-211        test            MUSK-211
   3              0   MUSK-212        test            MUSK-212
   4              0   MUSK-213        train           MUSK-213
                ...   ...             ...             ...
  87              1   NON-MUSK-j93    train           NON-MUSK-j93
  88              1   NON-MUSK-j96    train           NON-MUSK-j96
  89              1   NON-MUSK-j97    train           NON-MUSK-j97
  90              1   NON-MUSK-jp10   train           NON-MUSK-jp10
  91              1   NON-MUSK-jp13   train           NON-MUSK-jp13


92 rows x 4 columns
memory usage: 0.01 MB
type: getml.DataFrame

In [147]:
molecule.set_role(["class"], getml.data.roles.target)
molecule.set_role(["molecule_name"], getml.data.roles.join_key)
molecule.set_role(["molecule_name_2"], getml.data.roles.text)
molecule

name   molecule_name    class   molecule_name_2   split
role        join_key   target   text              unused_string
   0        MUSK-188        0   MUSK-188          train
   1        MUSK-190        0   MUSK-190          test
   2        MUSK-211        0   MUSK-211          test
   3        MUSK-212        0   MUSK-212          test
   4        MUSK-213        0   MUSK-213          train
                 ...      ...   ...               ...
  87    NON-MUSK-j93        1   NON-MUSK-j93      train
  88    NON-MUSK-j96        1   NON-MUSK-j96      train
  89    NON-MUSK-j97        1   NON-MUSK-j97      train
  90   NON-MUSK-jp10        1   NON-MUSK-jp10     train
  91   NON-MUSK-jp13        1   NON-MUSK-jp13     train


92 rows x 4 columns
memory usage: 0.00 MB
type: getml.DataFrame

Peripheral tables,

In [148]:
conformation.set_role(["conformation_name"], getml.data.roles.text)
conformation.set_role(["molecule_name"], getml.data.roles.join_key)
conformation.set_role(["f1", "f2", "f3", "f4", "f5", "f6", "f7", "f8", "f9", "f10", "f11", "f12", "f13",
"f14", "f15", "f16", "f17", "f18", "f19", "f20", "f21", "f22", "f23", "f24", "f25",
"f26", "f27", "f28", "f29", "f30", "f31", "f32", "f33", "f34", "f35", "f36", "f37",
"f38", "f39", "f40", "f41", "f42", "f43", "f44", "f45", "f46", "f47", "f48", "f49",
"f50", "f51", "f52", "f53", "f54", "f55", "f56", "f57", "f58", "f59", "f60", "f61",
"f62", "f63", "f64", "f65", "f66", "f67", "f68", "f69", "f70", "f71", "f72", "f73",
"f74", "f75", "f76", "f77", "f78", "f79", "f80", "f81", "f82", "f83", "f84", "f85",
"f86", "f87", "f88", "f89", "f90", "f91", "f92", "f93", "f94", "f95", "f96", "f97",
"f98", "f99", "f100", "f101", "f102", "f103", "f104", "f105", "f106", "f107",
"f108", "f109", "f110", "f111", "f112", "f113", "f114", "f115", "f116", "f117",
"f118", "f119", "f120", "f121", "f122", "f123", "f124", "f125", "f126", "f127",
"f128", "f129", "f130", "f131", "f132", "f133", "f134", "f135", "f136", "f137",
"f138", "f139", "f140", "f141", "f142", "f143", "f144", "f145", "f146", "f147",
"f148", "f149", "f150", "f151", "f152", "f153", "f154", "f155", "f156", "f157",
"f158", "f159", "f160", "f161", "f162", "f163", "f164", "f165", "f166"], getml.data.roles.numerical)

conformation

name   molecule_name          f1          f2          f3   ...        f163        f164        f165        f166
role        join_key   numerical   numerical   numerical   ...   numerical   numerical   numerical   numerical
   0        MUSK-188          42       -198        -109    ...          48        -37           6          30
   1        MUSK-188          42       -191        -142    ...          48        -37           5          30
   2        MUSK-188          42       -191        -142    ...          48        -37           5          31
   3        MUSK-188          42       -198        -110    ...          48        -37           6          30
   4        MUSK-190          42       -198        -102    ...          43        -30          14          26
                 ...         ...         ...         ...               ...         ...         ...         ...
 471   NON-MUSK-jp13          49       -199        -161    ...          47        -43         -15         -10
 472   NON-MUSK-jp13          38       -123        -139    ...          79        -28           4          74
 473   NON-MUSK-jp13          43       -102         -20    ...          55        -37         -19         -36
 474   NON-MUSK-jp13          39        -58          27    ...          79        -28           3          74
 475   NON-MUSK-jp13          52       -121         -24    ...          98        -14          12          96

name   conformation_name
role   text
   0   188_1+1
   1   188_1+2
   2   188_1+3
   3   188_1+4
   4   190_1+1
       ...
 471   jp13_1+4
 472   jp13_2+1
 473   jp13_2+2
 474   jp13_2+3
 475   jp13_2+4


476 rows x 168 columns
memory usage: 0.64 MB
type: getml.DataFrame

The next step is to define the data model. Refer to [https://relational.fel.cvut.cz/dataset/MuskSmall](https://relational.fel.cvut.cz/dataset/MuskSmall)
for a description of the dataset.

In [149]:
dm = getml.data.DataModel(population=molecule.to_placeholder())
dm.add(getml.data.to_placeholder(conformation))

dm.population.join(dm.conformation, on="molecule_name")
dm

molecule:
  columns:
  - molecule_name: join_key
  - class: target
  - molecule_name_2: text
  - split: unused_string

  joins:
  - right: 'conformation'
    on:
    - (molecule.molecule_name, conformation.molecule_name)
    relationship: 'many-to-many'
    lagged_targets: False

conformation:
  columns:
  - molecule_name: join_key
  - f1: numerical
  - f2: numerical
  - f3: numerical
  - f4: numerical
  - ...

Now we can create the container and add the tables to it.

In [150]:
container = getml.data.Container(population=molecule, split=molecule.split)
container.add(conformation)

container

population
    subset   name       rows   type
0   test     molecule     27   View
1   train    molecule     65   View

peripheral
    name           rows   type
0   conformation    476   DataFrame

In [151]:
fast_prop = getml.feature_learning.FastProp(
    loss_function=getml.feature_learning.loss_functions.CrossEntropyLoss,
)

predictor = getml.predictors.XGBoostClassifier()

In [152]:
text_field_splitter = getml.preprocessors.TextFieldSplitter()

pipe = getml.Pipeline(
    tags=['add-moleculate-name-2-as-text'],
    data_model=dm,
    feature_learners=[fast_prop],
    preprocessors=[text_field_splitter],
    predictors=[predictor],
    include_categorical=True,
)

pipe

Pipeline(data_model='molecule',
         feature_learners=['FastProp'],
         feature_selectors=[],
         include_categorical=True,
         loss_function='CrossEntropyLoss',
         peripheral=['conformation'],
         predictors=['XGBoostClassifier'],
         preprocessors=['TextFieldSplitter'],
         share_selected_features=0.5,
         tags=['add-moleculate-name-2-as-text'])

In [153]:
# getml.pipeline.delete('ZcUDIh')

In [154]:
pipe.fit(container.train)

Checking data model...

OK.

Output()

Output()

Output()

Output()

Output()

Trained pipeline.

Time taken: 0:00:00.699778.

Pipeline(data_model='molecule',
         feature_learners=['FastProp'],
         feature_selectors=[],
         include_categorical=True,
         loss_function='CrossEntropyLoss',
         peripheral=['conformation'],
         predictors=['XGBoostClassifier'],
         preprocessors=['TextFieldSplitter'],
         share_selected_features=0.5,
         tags=['add-moleculate-name-2-as-text', 'container-a9U4Uq'])

In [155]:
pipe.score(container.test)

Output()

Output()

    date time             set used   target   accuracy   auc   cross entropy
0   2025-02-05 15:05:15   train      class          1.0    1.0         0.0319
1   2025-02-05 15:05:16   test       class          1.0    1.0         0.03235