In [141]:
import getml
from challenge.utils.data import load_ctu_dataset

getml.set_project("pima")

Connected to project 'pima'.

# Task: Pima
### Dataset Description
>
> The *Pima* dataset is a well-known dataset used for medical research, specifically focusing on diabetes prediction among Pima Indian women. It originates from a study conducted by the National Institute of Diabetes and Digestive and Kidney Diseases.
> 
> **Data Model:**
> - The dataset is organized into multiple tables: `age`, `bmi`, `diastolic`, `numPreg`, `pedigree`, `plasma`, `serum`, `tricepts`, and `pima`.
> - Each table contains two columns: `arg1` (varchar) and `arg2` (decimal for most tables, varchar for `pima`).
> 
> **Task and Target Column:**
> - The primary task is *classification*, aiming to predict the presence of diabetes.
> - The target column is `arg2` in the `pima` table.
> 
> **Column Types:**
> - The dataset includes:
>   - *Varchar* (e.g., `arg1`)
>   - *Decimal* (e.g., `arg2` in most tables)
> 
> **Metadata:**
> - Size: 700 KB
> - Number of tables: 9
> - Total number of rows: 6,912
> - Total number of columns: 18
> - Missing values: No
> - Target table: `pima`
> - Target ID: `arg1`
> 
> **Research and Usage:**
> - The dataset is widely used in medical research for developing models to predict diabetes.
> - It is a popular choice for testing classification algorithms due to its real-world medical data.
> 
> This dataset provides a valuable resource for exploring medical data analysis, particularly in predicting diabetes based on various health indicators.

### Tables
Population table: pima

<h4>
  <details open>
     <summary>ER Diagram</summary>
       <img src="https://relational.fel.cvut.cz/assets/img/datasets-generated/Pima.svg" alt="Pima ER Diagram">
   </details>
</h4>

To load the dataset, we use the `load_ctu_dataset` function from the `utils`
module. This function returns a tuple with the population table as the first
element and the a dictionary of peripheral tables as the second element.

In [142]:
pima, peripheral = load_ctu_dataset("Pima")

(
    age,
    bmi,
    diastolic,
    numPreg,
    pedigree,
    plasma,
    serum,
    tricepts,
) = peripheral.values()

num_preg = numPreg.with_name("num_preg").to_df("num_preg")
peripheral["num_preg"] = num_preg

Analyzing schema:   0%|          | 0/9 [00:00<?, ?it/s]

Downloading tables:   0%|          | 0/9 [00:00<?, ?it/s]

Building data:   0%|          | 0/9 [00:00<?, ?it/s]

Now, we can inspect all tables and annotate the columns with [roles](https://getml.com/latest/user_guide/concepts/annotating_data/).

The population table (`pima`).

We already set the `target` role for the target (`arg2`).


arg2 is the target column for a binary classification task.

In [144]:
pima.set_role("arg1", getml.data.roles.join_key)
pima.set_role("arg2", getml.data.roles.target)
pima

name       arg1     arg2   split
role   join_key   target   unused_string
   0         A1        0   train
   1        A10        0   train
   2       A100        0   train
   3       A101        0   train
   4       A102        1   train
            ...      ...   ...
 763        A95        1   val
 764        A96        1   train
 765        A97        1   val
 766        A98        1   train
 767        A99        1   train


768 rows x 3 columns
memory usage: 0.02 MB
type: getml.DataFrame

Peripheral tables,

In [145]:
age.set_role("arg1", getml.data.roles.join_key)
age.set_role("arg2", getml.data.roles.numerical)
age

name       arg1        arg2
role   join_key   numerical
   0         A1          50
   1        A10          54
   2       A100          31
   3       A101          33
   4       A102          22
            ...         ...
 763        A95          21
 764        A96          40
 765        A97          24
 766        A98          22
 767        A99          23


768 rows x 2 columns
memory usage: 0.01 MB
type: getml.DataFrame

In [146]:
bmi.set_role("arg1", getml.data.roles.join_key)
bmi.set_role("arg2", getml.data.roles.numerical)
bmi

name       arg1        arg2
role   join_key   numerical
   0         A1        33.6
   1        A10         0
   2       A100        49.7
   3       A101        39
   4       A102        26.1
            ...        ...
 763        A95        24.7
 764        A96        33.9
 765        A97        31.6
 766        A98        20.4
 767        A99        28.7


768 rows x 2 columns
memory usage: 0.01 MB
type: getml.DataFrame

In [147]:
diastolic.set_role("arg1", getml.data.roles.join_key)
diastolic.set_role("arg2", getml.data.roles.numerical)
diastolic

name       arg1        arg2
role   join_key   numerical
   0         A1          72
   1        A10          96
   2       A100          90
   3       A101          72
   4       A102          60
            ...         ...
 763        A95          82
 764        A96          72
 765        A97          62
 766        A98          48
 767        A99          50


768 rows x 2 columns
memory usage: 0.01 MB
type: getml.DataFrame

In [148]:
num_preg.set_role("arg1", getml.data.roles.join_key)
num_preg.set_role("arg2", getml.data.roles.numerical)
num_preg

name       arg1        arg2
role   join_key   numerical
   0         A1           6
   1        A10           8
   2       A100           1
   3       A101           1
   4       A102           1
            ...         ...
 763        A95           2
 764        A96           6
 765        A97           2
 766        A98           1
 767        A99           6


768 rows x 2 columns
memory usage: 0.01 MB
type: getml.DataFrame

In [149]:
pedigree.set_role("arg1", getml.data.roles.join_key)
pedigree.set_role("arg2", getml.data.roles.numerical)
pedigree

name       arg1        arg2
role   join_key   numerical
   0         A1       0.627
   1        A10       0.232
   2       A100       0.325
   3       A101       1.222
   4       A102       0.179
            ...      ...
 763        A95       0.761
 764        A96       0.255
 765        A97       0.13
 766        A98       0.323
 767        A99       0.356


768 rows x 2 columns
memory usage: 0.01 MB
type: getml.DataFrame

In [150]:
plasma.set_role("arg1", getml.data.roles.join_key)
plasma.set_role("arg2", getml.data.roles.numerical)
plasma

name       arg1        arg2
role   join_key   numerical
   0         A1         148
   1        A10         125
   2       A100         122
   3       A101         163
   4       A102         151
            ...         ...
 763        A95         142
 764        A96         144
 765        A97          92
 766        A98          71
 767        A99          93


768 rows x 2 columns
memory usage: 0.01 MB
type: getml.DataFrame

In [151]:
serum.set_role("arg1", getml.data.roles.join_key)
serum.set_role("arg2", getml.data.roles.numerical)
serum

name       arg1        arg2
role   join_key   numerical
   0         A1           0
   1        A10           0
   2       A100         220
   3       A101           0
   4       A102           0
            ...         ...
 763        A95          64
 764        A96         228
 765        A97           0
 766        A98          76
 767        A99          64


768 rows x 2 columns
memory usage: 0.01 MB
type: getml.DataFrame

In [152]:
tricepts.set_role("arg1", getml.data.roles.join_key)
tricepts.set_role("arg2", getml.data.roles.numerical)
tricepts

name       arg1        arg2
role   join_key   numerical
   0         A1          35
   1        A10           0
   2       A100          51
   3       A101           0
   4       A102           0
            ...         ...
 763        A95          18
 764        A96          27
 765        A97          28
 766        A98          18
 767        A99          30


768 rows x 2 columns
memory usage: 0.01 MB
type: getml.DataFrame

The next step is to define the data model. Refer to [https://relational.fel.cvut.cz/dataset/Pima](https://relational.fel.cvut.cz/dataset/Pima)
for a description of the dataset.

In [153]:
dm = getml.data.DataModel(population=pima.to_placeholder())
dm.add(getml.data.to_placeholder(**peripheral))

dm.population.join(dm.age, on="arg1", relationship=getml.data.relationship.one_to_one)
dm.population.join(dm.bmi, on="arg1", relationship=getml.data.relationship.one_to_one)
dm.population.join(dm.diastolic, on="arg1", relationship=getml.data.relationship.one_to_one)
dm.population.join(dm.num_preg, on="arg1", relationship=getml.data.relationship.one_to_one)
dm.population.join(dm.pedigree, on="arg1", relationship=getml.data.relationship.one_to_one)
dm.population.join(dm.plasma, on="arg1", relationship=getml.data.relationship.one_to_one)
dm.population.join(dm.serum, on="arg1", relationship=getml.data.relationship.one_to_one)
dm.population.join(dm.tricepts, on="arg1", relationship=getml.data.relationship.one_to_one)

dm

pima:
  columns:
  - arg1: join_key
  - arg2: target
  - split: unused_string

  joins:
  - right: 'age'
    on:
    - (pima.arg1, age.arg1)
    relationship: 'one-to-one'
    lagged_targets: False
  - right: 'bmi'
    on:
    - (pima.arg1, bmi.arg1)
    relationship: 'one-to-one'
    lagged_targets: False
  - right: 'diastolic'
    on:
    - (pima.arg1, diastolic.arg1)
    relationship: 'one-to-one'
    lagged_targets: False
  - right: 'num_preg'
    on:
    - (pima.arg1, num_preg.arg1)
    relationship: 'one-to-one'
    lagged_targets: False
  - right: 'pedigree'
    on:
    - (pima.arg1, pedigree.arg1)
    relationship: 'one-to-one'
    lagged_targets: False
  - right: 'plasma'
    on:
    - (pima.arg1, plasma.arg1)
    relationship: 'one-to-one'
    lagged_targets: False
  - right: 'serum'
    on:
    - (pima.arg1, serum.arg1)
    relationship: 'one-to-one'
    lagged_targets: False
  - right: 'tricepts'
    on:
    - (pima.arg1, tricepts.arg1)
    relationship: 'one-to-one'
    lagged_targets: False

age:
  columns:
  - arg1: join_key
  - arg2: numerical

bmi:
  columns:
  - arg1: join_key
  - arg2: numerical

diastolic:
  columns:
  - arg1: join_key
  - arg2: numerical

num_preg:
  columns:
  - arg1: join_key
  - arg2: numerical

pedigree:
  columns:
  - arg1: join_key
  - arg2: numerical

plasma:
  columns:
  - arg1: join_key
  - arg2: numerical

serum:
  columns:
  - arg1: join_key
  - arg2: numerical

tricepts:
  columns:
  - arg1: join_key
  - arg2: numerical

Now we can create the container and add the tables to it.

In [154]:
container = getml.data.Container(population=pima, split=pima.split)
container.add(**peripheral)

container

population
    subset   name   rows   type
0   train    pima    538   View
1   val      pima    230   View

peripheral
    name        rows   type
0   age          768   DataFrame
1   bmi          768   DataFrame
2   diastolic    768   DataFrame
3   num_preg     768   DataFrame
4   pedigree     768   DataFrame
5   plasma       768   DataFrame
6   serum        768   DataFrame
7   tricepts     768   DataFrame

In [155]:
pipe = getml.pipeline.Pipeline(
    tags=["base_pipeline"],
    data_model=dm,
    predictors=getml.predictors.XGBoostClassifier(), 
    share_selected_features=0.5,
)

# .check(...) does an analysis on the pipeline, data model and container
# to see if everything is consistent (time relationships, roles, table joins, etc.).
# We pass the 'train' subset for verification
pipe.check(container.train)

Checking data model...

OK.

In [156]:
# .fit(...) orchestrates learning the features, and training the prediction model.

pipe.fit(container.train, check=False)

  Staging... ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 100% • 00:00
  XGBoost: Training as predictor... ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 100% • 00:00

Trained pipeline.

Time taken: 0:00:00.629088.

Pipeline(data_model='pima',
         feature_learners=[],
         feature_selectors=[],
         include_categorical=False,
         loss_function='SquareLoss',
         peripheral=['age', 'bmi', 'diastolic', 'num_preg', 'pedigree', 'plasma',
                     'serum', 'tricepts'],
         predictors=['XGBoostClassifier'],
         preprocessors=[],
         share_selected_features=0.5,
         tags=['base_pipeline', 'container-4IWrXP'])

In [157]:
# We now evaluate the pipeline on the validation set:
pipe.score(container.val)

  Staging... ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 100% • 00:00
  Preprocessing... ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 100% • 00:00

    date time             set used   target   accuracy       auc   cross entropy
0   2025-02-17 14:56:58   train      arg2       0.8996    0.9682          0.2679
1   2025-02-17 14:56:59   val        arg2       0.7826    0.8124          0.5124